link:
  rails_home_link: "http://www.railstutorial.org/"
  rails_about_link: "http://www.railstutorial.org/about"
  rails_contact_link: "http://www.railstutorial.org/contact"
  rails_help_link: "http://www.railstutorial.org/help"
  rails_book_link: "http://www.railstutorial.org/book"
  rails_author_link: "https://www.michaelhartl.com/"
  gravatar_email_link: "http://gravatar.com/emails"
name:
  max_length: 50
email:
  max_length: 255
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
password:
  min_length: 5
avatar:
  default_size: 80
  list_size: 50
  list_micropost_size: 50
pagination:
  per_number: 10
password_reset:
  expired_time: 2
micropost:
  max_length: 140
image:
  size: 5
  limit: [500, 500]
image_restricted_types:
  - image/jpeg
  - image/gif
  - image/png
