link:
  rails_home_link: "http://www.railstutorial.org/"
  rails_about_link: "http://www.railstutorial.org/about"
  rails_contact_link: "http://www.railstutorial.org/contact"
  rails_help_link: "http://www.railstutorial.org/help"
  rails_book_link: "http://www.railstutorial.org/book"
  rails_author_link: "https://www.michaelhartl.com/"
