link:
  rails_home_link: "http://www.railstutorial.org/"
  rails_about_link: "http://www.railstutorial.org/about"
  rails_contact_link: "http://www.railstutorial.org/contact"
  rails_help_link: "http://www.railstutorial.org/help"
  rails_book_link: "http://www.railstutorial.org/book"
  rails_author_link: "https://www.michaelhartl.com/"
name:
  max_length: 50
email:
  max_length: 255
  valid_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
password:
  min_length: 5
